sonar.projectKey=Waluh-Corporation_timesheet-generator
sonar.organization=waluh-corporation
sonar.projectName=timesheet-backend

# Source code and exclusions
sonar.sources=.
sonar.exclusions=**/*_test.go,docs/**,assets/**,scripts/**,tmp/**,templates/**,database/schema_dump.sql

# Test files configuration
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Go test coverage report path from CI
sonar.go.coverage.reportPaths=coverage.out

# Disable PL/SQL analyzer from analyzing PostgreSQL files as Oracle PL/SQL
sonar.plsql.file.suffixes=-

# Source encoding
sonar.sourceEncoding=UTF-8

