sonar.projectKey=Waluh-Corporation_timesheet-generator
sonar.organization=waluh-corporation
sonar.projectName=timesheet-backend

# Source code and exclusions
sonar.sources=.
sonar.exclusions=**/*_test.go,docs/**,assets/**,scripts/**,tmp/**,templates/**

# Test files configuration
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Go test coverage report path from CI
sonar.go.coverage.reportPaths=coverage.out

# Source encoding
sonar.sourceEncoding=UTF-8
