sonar.projectKey=khw315_timesheet-generator
sonar.organization=khw315
sonar.projectName=timesheet-generator

# Source and test paths
sonar.sources=backend,frontend/src
sonar.tests=backend
sonar.test.inclusions=backend/**/*_test.go

# Go coverage configuration
sonar.go.coverage.reportPaths=backend/coverage.out

# Exclusions
sonar.exclusions=**/*.xlsx,frontend/.next/**,frontend/out/**,frontend/node_modules/**,**/assets/**,**/*_test.go
sonar.coverage.exclusions=**/*_test.go,**/assets/**
